package jp.co.smartservice.domain.repository;

import java.util.List;
import jp.co.smartservice.domain.model.T001User;
import jp.co.smartservice.domain.model.T001UserExample;
import jp.co.smartservice.domain.model.T001UserKey;
import org.apache.ibatis.annotations.Param;

public interface T001UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int countByExample(T001UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int deleteByExample(T001UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int deleteByPrimaryKey(T001UserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int insert(T001User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int insertSelective(T001User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	List<T001User> selectByExample(T001UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	T001User selectByPrimaryKey(T001UserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int updateByExampleSelective(@Param("record") T001User record, @Param("example") T001UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int updateByExample(@Param("record") T001User record, @Param("example") T001UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int updateByPrimaryKeySelective(T001User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t001_user
	 * @mbggenerated  Fri Aug 14 01:29:43 JST 2015
	 */
	int updateByPrimaryKey(T001User record);
}