package jp.co.smartservice.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.smartservice.domain.model.T900Todo;
import jp.co.smartservice.domain.model.T900TodoExample;
import jp.co.smartservice.domain.model.T900TodoKey;

public interface T900TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int countByExample(T900TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int deleteByExample(T900TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int deleteByPrimaryKey(T900TodoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int insert(T900Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int insertSelective(T900Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    List<T900Todo> selectByExample(T900TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    T900Todo selectByPrimaryKey(T900TodoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int updateByExampleSelective(@Param("record") T900Todo record, @Param("example") T900TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int updateByExample(@Param("record") T900Todo record, @Param("example") T900TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int updateByPrimaryKeySelective(T900Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    int updateByPrimaryKey(T900Todo record);

	/**
    *
    * @param example
    * @param rowBounds
    * @return
    */
    List<T900Todo> findPageByExample(T900TodoExample example, RowBounds rowBounds);
}