package jp.co.smartservice.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.co.smartservice.domain.model.Todo;
import jp.co.smartservice.domain.model.TodoExample;
import jp.co.smartservice.domain.model.TodoKey;

public interface TodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int deleteByPrimaryKey(TodoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    Todo selectByPrimaryKey(TodoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo
     *
     * @mbggenerated Wed Aug 12 23:25:20 JST 2015
     */
    int updateByPrimaryKey(Todo record);

    /**
    *
    * @param example
    * @param rowBounds
    * @return
    */
    List<Todo> findPageByExample(TodoExample example, RowBounds rowBounds);
}