package jp.co.smartservice.domain.model;

import java.io.Serializable;

public class T900TodoKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t900_todo.todo_id
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    private String todoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t900_todo
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t900_todo.todo_id
     *
     * @return the value of t900_todo.todo_id
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    public String getTodoId() {
        return todoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t900_todo.todo_id
     *
     * @param todoId the value for t900_todo.todo_id
     *
     * @mbggenerated Fri Aug 14 01:48:20 JST 2015
     */
    public void setTodoId(String todoId) {
        this.todoId = todoId;
    }
}